ralphtheninja/open-funding

README.md
Great resource to get up to speed on the subject
=> Add Holger's talk

README.md
Added in a couple more grant-based OSS funding initiatives that I know of: MOSS (from Mozilla) and CII (a project of Linux).
=> added MOSS and CII as grant funding sources

README.md
Closes https://github.com/ralphtheninja/open-funding/issues/5
=> add DAT description

README.md
Solves https://github.com/ralphtheninja/open-funding/issues/18
=> add Software Freedom Conservancy

README.md
fixes #29 
For now this tiny PR. I thought about adding more info, but not sure whatever it should be directly here or published elsewhere and just linked here.
For example my proposal was not something that was obviously on topic (decent part of it was explanation why "improving an OpenStreetMap editor" counts as "privacy enhancing technology").
=> add StreetComplete as a funded project

README.md
note - for NGI Assure I summarized description as title itself is not clear
=> update open funding submissions operated by NGI0

README.md
done with agreement of mentioned person
=> expand StreetComplete info

README.md
Fixes #37 
More PRs to come :D
=> Add GitHub sponsors

README.md
=> Add Prototype Fund

README.md
See https://www.coreinfrastructure.org/
Supposed replacement seems to not be offering actual support for open source projects,
and appears to be limited to corporate blabla 
> How is OpenSSF ensuring inclusive representation of the open source community?
> Diversity, Inclusion, and Representation is one of our core values.
https://openssf.org/
(though if actual support is present somewhere, it would be
worth including - but https://duckduckgo.com/?t=ffab&q=grant+funding+site%3Aopenssf.org%20!g 
and
https://duckduckgo.com/?t=ffab&q=grant+funding+site%3Aopenssf.org&ia=web
finds nothing)
=> Core Infrastructure Initiative was shut down

README.md
This is an open fund right now! 
https://fordfoundation.forms.fm/2024-digital-infrastructure-insights-fund-rfp/forms/9861
=> Adding DIIF Fund (Deadline: June 2)

README.md
And made a new temporary section. Closes #55. 
How did you make the ToC @ralphtheninja? It seems to be out of sync.
=> docs: Adding OTF I&EH RFP

.gitignore, .npmrc, README.md, package.json
cc @RichardLitt 
see https://github.com/ralphtheninja/open-funding/pull/58
=> Add hallmark to fix toc by running `npm run toc`

README.md
I basically just cleaned up some things. We should maybe go through the list one by one and check that links are valid etc.
=> Tweak formatting

README.md
link was going to location where no actual info about this program was found
I was also unable to find a replacement or indicator this program is real
also, it is some crypto thingy
=> remove Cosmos hub grant program

README.md
=> Remove Spotify as there is no way to apply

README.md
Not needed. See https://github.com/ralphtheninja/open-funding/pull/68\#discussion_r1738555977.
=> refactor: Remove empty letter headers

README.md
does not appear to be viable funding source for OS based on what the want to fund
=> remove esmeefairbairn

README.md
see #81
> Probably dead? FIL is pretty low ATM.
fixes #81
=> remove filecoin as dead

README.md
"Sorry, this survey has already expired."
=> remove expired Google for AI

README.md
It is about Quantum Computing related projects, no focus whatsoever on open source
=> remove Unitary Fund as offtopic

README.md
=> remove Web We Want grants as dead

README.md
=> remove Global Innovation Fund

README.md
redirects to another private fiat
=> remove private fiat money grant project

README.md
=> remove duplicate of section above

README.md
- no focus on open source or mention of this
- no sign of activity in 2024
- already spend money
=> Remove FPH

README.md
Seems irrelevant. Closes #104.
=> fix: Remove cosmos

README.md
from looking at https://indela.fund/en/our-support/ it seems to be inactive nowadays
=> remove inactive Indela

README.md
> As an intermediary funder, MDF provides targeted grants and contracts to advocacy organizations working at the intersection of digital equity, tech accountability, and power building. MDF identifies emerging needs and provides grants quickly so organizations can take action and respond to threats as they happen.
https://mediademocracyfund.org/#priorities - grantmaking section
=> remove MDF as there is no real way to apply for OS projects

README.md
according to their website last awards were in 2019
=> remove Fire Africa

README.md
DIIF - Digital Infrastructure Grants @ Open collective
https://opencollective.com/di-grants is dead
https://fordfoundation.forms.fm/2024-digital-infrastructure-insights-fund-rfp/forms/9861 links  https://infrastructureinsights.fund/ which links
https://drive.google.com/file/d/191vNMY1bkBH2Tsqciyqj4xOrUf0MpqF9/view which has
"The next open calls are scheduled for
August/September 2023 and early 2024."
indicating that no more open calls are planned
=> DIIIF is gone

README.md
see https://meta.wikimedia.org/wiki/Grants:Programs/Wikimedia_Research_%26_Technology_Fund
=> Wikimedia Research & Technology Fund never existed

README.md
> Please note that Siegel Family Endowment does not currently accept unsolicited proposals.
https://www.siegelendowment.org/contact/
=> "Siegel (...) does not currently accept unsolicited proposals."

README.md
Because I do not think OSC should be in the main list.
=> Adding a Fiscal Hosting section
